image:
  file: .gitpod.Dockerfile

tasks:
  - name: aws-sso
    command: gp await-port 23000 && aws-sso
  - name: airflow
    init: cd .airflow; make build
    command: make airflow start

vscode:
  extensions:
    - GitHub.vscode-pull-request-github
    - ms-azuretools.vscode-docker
    - amazonwebservices.aws-toolkit-vscode
    - ms-python.python

ports:
  - port: 8080
    visibility: private
